const P=id=>document.getElementById(id),num=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
let recurring=null,patternPage=0;
function renderPatterns(){
 if(!recurring)return;const q=P('pattern-search').value.trim(),min=Number(P('pattern-min').value);
 const rows=recurring.patterns.filter(p=>p.occurrences>=min&&[p.src,p.mid,p.dst].some(g=>g.includes(q)));
 P('pattern-list').innerHTML=rows.slice(patternPage*8,patternPage*8+8).map(p=>`<details class="card pattern-card"><summary><h2>${p.src} → ${p.mid} → ${p.dst}</h2><span class="fold-hint"><span>Повторений</span>: ${p.occurrences}</span></summary><div class="pattern-story"><div><h3>Наблюдаемый факт</h3><p><span>Разные даты входа</span>: ${p.occurrences}. ${p.first} — ${p.last}.</p></div><div><h3>Гипотеза</h3><p>Регулярная передача средств через посредника.</p></div><div><h3>Альтернативное объяснение</h3><p>Повторяющиеся расчёты или разные платежи из общего остатка.</p></div></div><p class="note"><span>Что запросить</span>: <span>Назначения платежей, точное время, остатки и операции вне выборки.</span></p><div class="bounded-table table-wrap" tabindex="0"><table><thead><tr><th>Вход: дата</th><th>Выход: дата</th><th>Дней</th><th>A → B, KZT</th><th>B → C, KZT</th></tr></thead><tbody>${p.events.map(e=>`<tr><td>${e.in_date}</td><td>${e.out_date}</td><td>${e.lag_days}</td><td>${num(e.in_tiyn/100)}</td><td>${num(e.out_tiyn/100)}</td></tr>`).join('')}</tbody></table></div><div class="actions"><a class="primary" href="/analytics?gid=${p.mid}"><span>Открыть посредника</span> ↗</a><a class="secondary" href="/report?gid=${p.mid}"><span>Отчёт / PDF</span> ↗</a></div></details>`).join('')||'<p>Нет маршрутов по заданным условиям.</p>';
 P('pattern-count').textContent=`${rows.length?patternPage*8+1:0}–${Math.min(patternPage*8+8,rows.length)} / ${rows.length}`;
 P('pattern-prev').disabled=patternPage===0;P('pattern-next').disabled=(patternPage+1)*8>=rows.length;
 P('pattern-status').textContent='Маршруты отсортированы по числу повторений. Раскройте маршрут для просмотра операций.';
}
P('pattern-search').oninput=P('pattern-min').onchange=()=>{patternPage=0;renderPatterns();};
P('pattern-prev').onclick=()=>{patternPage--;renderPatterns();};P('pattern-next').onclick=()=>{patternPage++;renderPatterns();};
(async()=>{try{const r=await fetch('/api/patterns');if(!r.ok)throw Error('Выполните python recurring_patterns.py');recurring=await r.json();P('pattern-kpis').innerHTML=[['Повторяющиеся маршруты',recurring.count],['Максимум повторений',Math.max(0,...recurring.patterns.map(p=>p.occurrences))],['Окно между переводами','1–2'],['Шагов в маршруте','2']].map(([l,v])=>`<div class="card kpi"><label>${l}</label><strong>${v}</strong></div>`).join('');renderPatterns();}catch(e){P('pattern-status').textContent=e.message;}})();
