/* UI-only localization. Data, IDs, evidence strings and exports are never rewritten. */
(()=>{
const catalog=[
['Обзор','Overview','Шолу'],['Клиенты','Clients','Клиенттер'],['Цепочки','Routes','Тізбектер'],['По неделям','Weekly','Апталар'],['Повторы','Recurring routes','Қайталанатын тізбектер'],
['Светлая','Light','Ашық'],['Тёмная','Dark','Қараңғы'],['Классика','Classic','Классикалық'],['Аниме','Anime','Аниме'],['Тема','Theme','Тақырып'],['Стиль','Style','Стиль'],['Язык интерфейса','UI language','Интерфейс тілі'],
['Увидеть связи.','See the connections.','Байланыстарды көру.'],['Понять движение денег.','Understand the flow of money.','Ақша қозғалысын түсіну.'],['ОТ ДАННЫХ К ОБЪЯСНЕНИЮ','FROM DATA TO EXPLANATION','ДЕРЕКТЕН ТҮСІНДІРУГЕ'],
['Кто собирает средства, кто передаёт дальше и какие переводы связывают клиентов. Исследуйте граф и проверяйте каждую гипотезу по цифрам.','Who collects funds, who passes them on, and which transfers connect clients. Explore the graph and check each hypothesis against the numbers.','Қаражатты кім жинайды, кім әрі қарай жібереді және клиенттерді қандай аударымдар байланыстырады? Графты зерттеп, әр болжамды сандармен тексеріңіз.'],
['Исследовать клиентов ↗','Explore clients ↗','Клиенттерді зерттеу ↗'],['Найти цепочку →','Find a route →','Тізбекті табу →'],['ФРАГМЕНТ НАБЛЮДАЕМОГО ГРАФА','OBSERVED GRAPH FRAGMENT','БАҚЫЛАНҒАН ГРАФ ҮЗІНДІСІ'],
['Участники','Participants','Қатысушылар'],['Переводы','Transfers','Аударымдар'],['Оборот выборки','Observed turnover','Іріктеме айналымы'],['Сообщества','Communities','Қауымдастықтар'],['Клиенты в графе','Clients in the graph','Графтағы клиенттер'],['Сумма операций, не уникальный капитал','Sum of transfers, not unique capital','Операциялар сомасы, бірегей капитал емес'],['Группы по структуре переводов','Groups based on transfer structure','Аударым құрылымы бойынша топтар'],
['С чего начать исследование','Where to start','Зерттеуді неден бастау керек'],['Три вопроса к данным','Three questions for the data','Деректерге үш сұрақ'],['01 / УЧАСТНИКИ','01 / PARTICIPANTS','01 / ҚАТЫСУШЫЛАР'],['02 / ЦЕПОЧКИ','02 / ROUTES','02 / ТІЗБЕКТЕР'],['03 / СТРУКТУРА','03 / STRUCTURE','03 / ҚҰРЫЛЫМ'],
['Кого проверить первым?','Who should be reviewed first?','Алдымен кімді тексеру керек?'],['Как связаны два клиента?','How are two clients connected?','Екі клиент қалай байланысқан?'],['На ком держится сеть?','Which clients hold the network together?','Желі кімдерге тәуелді?'],
['Роли клиентов, приоритет и конкретные основания для каждого вывода.','Client roles, review priority and specific reasons for every conclusion.','Клиент рөлдері, басымдық және әр қорытындының нақты негіздері.'],['Последовательность направленных переводов с датами и суммами на каждом шаге.','A sequence of directed transfers with dates and amounts at every step.','Әр қадамда күні мен сомасы көрсетілген бағытталған аударымдар тізбегі.'],
['Изменение связности после удаления ключевых узлов в сравнении со случайным выбором.','Connectivity after removing key nodes, compared with random removal.','Негізгі түйіндерді жойғаннан кейінгі байланыстылық, кездейсоқ таңдаумен салыстыру.'],
['Открыть аналитику ↗','Open analytics ↗','Аналитиканы ашу ↗'],['Найти маршрут ↗','Find a route ↗','Бағытты табу ↗'],['Проверить устойчивость ↗','Check resilience ↗','Тұрақтылықты тексеру ↗'],['ГОТОВО ДЛЯ РАЗБОРА','READY TO EXPLORE','ТАЛДАУҒА ДАЙЫН'],['Три клиента. Три разные роли.','Three clients. Three different roles.','Үш клиент. Үш түрлі рөл.'],['Открыть примеры →','Open examples →','Мысалдарды ашу →'],
['Сборщик, транзит и координатор — примеры, выбранные алгоритмом. Разберите основания роли и проверьте ограничения.','Collector, transit and coordinator: examples selected by the algorithm. Review the role evidence and its limitations.','Жинаушы, транзит және үйлестіруші — алгоритм таңдаған мысалдар. Рөлдің негіздері мен шектеулерін тексеріңіз.'],
['Роли и маршруты — гипотезы по наблюдаемой выборке. Входящие seed неполны, граф ограничен четырьмя шагами и порогом 5 000 ₸. Приоритет не означает вероятность мошенничества.','Roles and routes are hypotheses based on the observed sample. Seed inflows are incomplete; the graph is limited to four hops and a 5,000 KZT threshold. Priority is not a fraud probability.','Рөлдер мен тізбектер — бақыланған іріктемеге негізделген болжамдар. Seed кірістері толық емес; граф төрт қадаммен және 5 000 ₸ шегімен шектелген. Басымдық алаяқтық ықтималдығын білдірмейді.'],
['ОБЗОР ДЕНЕЖНЫХ ПОТОКОВ','TRANSFER OVERVIEW','АҚША АҒЫНДАРЫНА ШОЛУ'],['За переводами — связи.','Connections behind the transfers.','Аударымдардың артындағы байланыстар.'],['Исследуйте движение средств, роли участников и сообщества внутри банковского графа. Каждый вывод сопровождается измеримыми признаками.','Explore money movements, participant roles and communities in the bank graph. Each conclusion includes measurable evidence.','Банк графындағы ақша қозғалысын, қатысушы рөлдерін және топтарды зерттеңіз. Әр қорытынды өлшенетін белгілермен түсіндіріледі.'],
['Объём переводов по дням','Daily transfer volume','Күндер бойынша аударым көлемі'],['Роли участников','Participant roles','Қатысушылардың рөлдері'],['Объяснимые правила · предварительные гипотезы','Explainable rules · preliminary hypotheses','Түсіндірілетін ережелер · бастапқы болжамдар'],['Сборщик','Collector','Жинаушы'],['Транзит','Transit','Транзит'],['Распределитель','Distributor','Таратушы'],['Конечный*','Terminal*','Соңғы алушы*'],['Координатор','Coordinator','Үйлестіруші'],['Периферия / ?','Peripheral / ?','Шеткі / ?'],
['Три случая для разбора','Three cases to explore','Талдауға арналған үш мысал'],['Кандидаты выбраны алгоритмом из результатов; нажмите для просмотра оснований.','Candidates were selected by the algorithm; click to inspect the evidence.','Үміткерлерді алгоритм таңдады; негіздерін көру үшін басыңыз.'],['Участники и приоритет проверки','Participants and review priority','Қатысушылар және тексеру басымдығы'],['Свернуть / раскрыть','Collapse / expand','Жию / ашу'],['Найти клиента по gid…','Find a client by gid…','Клиентті gid бойынша табу…'],['Поиск по gid','Search by gid','gid бойынша іздеу'],['Все роли','All roles','Барлық рөлдер'],['Роль','Role','Рөл'],['Кластер','Cluster','Кластер'],['Все сообщества','All communities','Барлық топтар'],['Все участники','All participants','Барлық қатысушылар'],['Граница выборки','Sample boundary','Іріктеме шекарасы'],['Без границы 4-го шага','Exclude fourth-hop boundary','Төртінші қадам шекарасынсыз'],['Только граница','Boundary only','Тек шекара'],
['Клиент / gid','Client / gid','Клиент / gid'],['Вход, ₸','Incoming, KZT','Кіріс, ₸'],['Выход, ₸','Outgoing, KZT','Шығыс, ₸'],['Связи вход / выход','Incoming / outgoing links','Кіріс / шығыс байланыстар'],['Приоритет','Priority','Басымдық'],['Группа','Group','Топ'],['← Назад','← Previous','← Алдыңғы'],['Далее →','Next →','Келесі →'],['Нет участников по заданным фильтрам','No clients match the filters','Сүзгілерге сәйкес клиенттер жоқ'],
['Почему эта роль:','Why this role:','Бұл рөлдің себебі:'],['Почему такой приоритет:','Why this priority:','Бұл басымдықтың себебі:'],['Сценарий транзита 1–2 дня:','1–2 day transit scenario:','1–2 күндік транзит сценарийі:'],['Что запросить:','Data to request:','Сұратылатын деректер:'],['Отчёт / PDF →','Report / PDF →','Есеп / PDF →'],['Динамика клиента по неделям →','Weekly client activity →','Клиенттің апталық белсенділігі →'],['Добавить в список проверки','Add to review list','Тексеру тізіміне қосу'],['Убрать из списка проверки','Remove from review list','Тексеру тізімінен алып тастау'],
['Цвет узлов','Node colors','Түйін түстері'],['Цвет по роли','Color by role','Рөл бойынша түс'],['Цвет по группе','Color by group','Топ бойынша түс'],['Область графа','Graph scope','Граф ауқымы'],['Связи клиента','Client connections','Клиент байланыстары'],['Группа клиента','Client community','Клиент тобы'],['Число связей','Link count','Байланыстар саны'],['20 крупнейших связей','20 largest links','Ең ірі 20 байланыс'],['Все связи','All links','Барлық байланыстар'],['Возможный транзит через 1–2 дня','Possible transit after 1–2 days','1–2 күннен кейінгі ықтимал транзит'],['Вход','Incoming','Кіріс'],['Выход','Outgoing','Шығыс'],['Дней','Days','Күн'],['Сопоставлено, ₸','Matched, KZT','Сәйкестендірілген, ₸'],['Все прямые связи','All direct connections','Барлық тікелей байланыстар'],['Отправитель','Sender','Жіберуші'],['Получатель','Recipient','Алушы'],['Сумма, ₸','Amount, KZT','Сома, ₸'],['Операций','Transfers','Операциялар'],['Наблюдаемых связей нет','No observed connections','Бақыланған байланыстар жоқ'],['Нет сопоставлений через 1–2 дня','No matches after 1–2 days','1–2 күндік сәйкестіктер жоқ'],
['Что произойдёт без ключевых узлов?','What happens without key nodes?','Негізгі түйіндерсіз не болады?'],['Сценарий','Scenario','Сценарий'],['Крупнейшая компонента','Largest component','Ең үлкен компонент'],['Компоненты','Components','Компоненттер'],['Изоляты','Isolates','Оқшау түйіндер'],['Случайное удаление: медиана (диапазон)','Random removal: median (range)','Кездейсоқ жою: медиана (ауқым)'],['Сообщества переводов','Transfer communities','Аударым топтары'],['Внутренний оборот, ₸','Internal turnover, KZT','Ішкі айналым, ₸'],['Гипотеза','Hypothesis','Болжам'],['Мой список на проверку','My review list','Менің тексеру тізімім'],['Действие','Action','Әрекет'],['Убрать','Remove','Алып тастау'],['Скачать список CSV','Download review CSV','Тізімді CSV түрінде жүктеу'],['Клиент добавлен в список проверки.','Client added to the review list.','Клиент тексеру тізіміне қосылды.'],['Клиент удалён из списка.','Client removed from the list.','Клиент тізімнен алынды.'],['Откройте карточку клиента и добавьте его в список.','Open a client card to add it to the list.','Тізімге қосу үшін клиент картасын ашыңыз.'],
['Проверка алгоритма на контрольных сценариях','Algorithm checks on control scenarios','Алгоритмді бақылау сценарийлерімен тексеру'],['Ожидаемая роль','Expected role','Күтілетін рөл'],['Результат','Result','Нәтиже'],['Статус','Status','Күй'],['Основание','Evidence','Негіздеме'],['Открыть полный отчёт →','Open full report →','Толық есепті ашу →'],['Разбор одного случая','Case study','Бір жағдайды талдау'],['Сценарий защиты','Demo script','Қорғау сценарийі'],['↓ Роли всех клиентов','↓ All client roles','↓ Барлық клиент рөлдері'],['↓ Роли клиентов','↓ Client roles','↓ Клиент рөлдері'],['↓ Сообщества','↓ Communities','↓ Топтар'],['↓ Топ-50 для проверки','↓ Top 50 for review','↓ Тексеруге арналған үздік 50'],['↓ Топ-50','↓ Top 50','↓ Үздік 50'],['↓ Сценарии 1–2 дня','↓ 1–2 day scenarios','↓ 1–2 күндік сценарийлер'],
['ПРОВЕРКА СВЯЗЕЙ','CONNECTION EXPLORER','БАЙЛАНЫСТАРДЫ ТЕКСЕРУ'],['От клиента к клиенту.','From client to client.','Клиенттен клиентке.'],['Отправитель · gid','Sender · gid','Жіберуші · gid'],['Получатель · gid','Recipient · gid','Алушы · gid'],['Идентификатор клиента','Client ID','Клиент идентификаторы'],['Не больше переводов','Maximum transfers','Аударымдардың ең көп саны'],['Пауза между переводами','Gap between transfers','Аударымдар арасындағы үзіліс'],['1 день','1 day','1 күн'],['До 2 дней','Up to 2 days','2 күнге дейін'],['До 7 дней','Up to 7 days','7 күнге дейін'],['До 31 дня','Up to 31 days','31 күнге дейін'],['Начало периода','Start date','Басталу күні'],['Конец периода','End date','Аяқталу күні'],['Подставить пример из данных','Use an example from the data','Деректерден мысал таңдау'],['Выберите клиентов или воспользуйтесь примером из выборки.','Choose clients or use an example from the sample.','Клиенттерді таңдаңыз немесе іріктемедегі мысалды қолданыңыз.'],['← Вернуться к анализу клиентов','← Back to client analytics','← Клиенттер аналитикасына оралу'],['Шаг','Step','Қадам'],['Дата','Date','Күні'],['Ищем последовательность переводов…','Searching for a sequence of transfers…','Аударымдар тізбегін іздеуде…'],['Даты возрастают на каждом шаге. Показана одна из кратчайших цепочек в заданных пределах.','Dates increase at each step. One of the shortest routes within the selected limits is shown.','Әр қадамда күндер өседі. Таңдалған шектердегі ең қысқа тізбектердің бірі көрсетілген.'],
['ИЗМЕНЕНИЯ АКТИВНОСТИ','ACTIVITY CHANGES','БЕЛСЕНДІЛІК ӨЗГЕРІСТЕРІ'],['Что изменилось за неделю?','What changed this week?','Апта ішінде не өзгерді?'],['Базовая неделя','Baseline week','Базалық апта'],['Сравниваемая неделя','Comparison week','Салыстырылатын апта'],['Способ сравнения','Comparison mode','Салыстыру тәсілі'],['В среднем за день','Daily average','Күндік орташа'],['Итого за неделю','Weekly total','Апталық жиынтық'],['Сравнить →','Compare →','Салыстыру →'],['Динамика всего графа','Whole-network activity','Бүкіл графтың динамикасы'],['Изменения по клиентам','Changes by client','Клиенттер бойынша өзгерістер'],['Клиент по gid','Client by gid','gid бойынша клиент'],['Изменение активности','Activity change','Белсенділік өзгерісі'],['Все изменения','All changes','Барлық өзгерістер'],['Рост активности','Activity increase','Белсенділіктің өсуі'],['Снижение активности','Activity decrease','Белсенділіктің төмендеуі'],['Без операций в базовой неделе','No baseline-week transfers','Базалық аптада операциялар жоқ'],['Сортировка изменений','Sort changes','Өзгерістерді сұрыптау'],['По изменению суммы','By amount change','Сома өзгерісі бойынша'],['По изменению числа операций','By transfer-count change','Операциялар санының өзгерісі бойынша'],['По числу новых контрагентов','By new counterparties','Жаңа контрагенттер саны бойынша'],['Изменение суммы','Amount change','Сома өзгерісі'],['Операции: база → сравнение','Transfers: baseline → comparison','Операциялар: база → салыстыру'],['Контрагенты: база → сравнение','Counterparties: baseline → comparison','Контрагенттер: база → салыстыру'],['Новые / ушедшие*','New / lost*','Жаңа / кеткен*'],['Нет базы','No baseline','База жоқ'],['Нет результатов','No results','Нәтижелер жоқ'],['Изменение оборота','Turnover change','Айналым өзгерісі'],['Активные клиенты','Active clients','Белсенді клиенттер'],['Базовая неделя должна быть раньше сравниваемой','The baseline week must precede the comparison week','Базалық апта салыстырылатын аптадан бұрын болуы керек'],
['ПРОВЕРЯЕМЫЕ ГИПОТЕЗЫ','TESTABLE HYPOTHESES','ТЕКСЕРІЛЕТІН БОЛЖАМДАР'],['Одна цепочка. Несколько повторений.','One route. Multiple occurrences.','Бір тізбек. Бірнеше қайталану.'],
['Находим A → B → C, когда переводы через одного посредника повторяются в разные дни. Каждую гипотезу можно проверить по датам и суммам.','Find A → B → C when transfers through the same intermediary recur on different days. Check each hypothesis against dates and amounts.','Бір делдал арқылы аударымдар әртүрлі күндері қайталанғанда A → B → C тізбегін табамыз. Әр болжамды күндер мен сомалар бойынша тексеруге болады.'],
['Повторяемость не доказывает движение одних и тех же денег. Операции агрегируются по паре и дню. Между входом и выходом — 1–2 дня; одна дата на каждой стороне используется один раз внутри маршрута. Между разными маршрутами операции могут пересекаться.','Recurrence does not prove that the same money moved. Transfers are grouped by directed pair and day. Inflow and outflow are 1–2 days apart; each date on either side is used once per route. Different routes can share operations.','Қайталану бір ақшаның қозғалысын дәлелдемейді. Операциялар бағытталған жұп пен күн бойынша біріктіріледі. Кіріс пен шығыс арасы 1–2 күн; әр тараптағы күн бір тізбекте бір рет қолданылады. Әртүрлі тізбектерде ортақ операциялар болуы мүмкін.'],
['Повторяющиеся маршруты','Recurring routes','Қайталанатын тізбектер'],['Максимум повторений','Most occurrences','Ең көп қайталану'],['Окно между переводами','Gap between transfers','Аударымдар арасындағы аралық'],['Шагов в маршруте','Steps per route','Тізбектегі қадамдар'],['Поиск участника маршрута','Search route participant','Тізбек қатысушысын іздеу'],['Найти участника по gid…','Find participant by gid…','Қатысушыны gid бойынша табу…'],['Минимум повторений','Minimum occurrences','Ең аз қайталану'],['От 2 повторений','At least 2 occurrences','Кемінде 2 қайталану'],['От 3 повторений','At least 3 occurrences','Кемінде 3 қайталану'],['От 4 повторений','At least 4 occurrences','Кемінде 4 қайталану'],['Загрузка…','Loading…','Жүктелуде…'],['Повторений','Occurrences','Қайталану'],['Наблюдаемый факт','Observed fact','Бақыланған факт'],['Разные даты входа','Distinct inflow dates','Әртүрлі кіріс күндері'],['Регулярная передача средств через посредника.','Regular transfer of funds through an intermediary.','Делдал арқылы қаражатты тұрақты аудару.'],['Альтернативное объяснение','Alternative explanation','Баламалы түсіндірме'],['Повторяющиеся расчёты или разные платежи из общего остатка.','Recurring settlements or unrelated payments from a shared balance.','Қайталанатын есеп айырысулар немесе ортақ қалдықтан жасалған әртүрлі төлемдер.'],['Что запросить','Data to request','Сұратылатын деректер'],['Назначения платежей, точное время, остатки и операции вне выборки.','Payment purposes, exact times, balances and operations outside the sample.','Төлем мақсаттары, нақты уақыт, қалдықтар және іріктемеден тыс операциялар.'],['Вход: дата','Inflow date','Кіріс күні'],['Выход: дата','Outflow date','Шығыс күні'],['Открыть посредника','Open intermediary','Делдалды ашу'],['Отчёт / PDF','Report / PDF','Есеп / PDF'],['Нет маршрутов по заданным условиям.','No routes match the selected criteria.','Таңдалған шарттарға сәйкес тізбектер жоқ.'],['Маршруты отсортированы по числу повторений. Раскройте маршрут для просмотра операций.','Routes are sorted by occurrence count. Expand a route to inspect its operations.','Тізбектер қайталану саны бойынша сұрыпталған. Операцияларды көру үшін тізбекті ашыңыз.'],['Как читать этот сигнал','How to interpret this signal','Бұл белгіні қалай түсіндіруге болады'],
['Факт — повторяющийся порядок переводов. Гипотеза — регулярная передача средств через посредника. Альтернатива — обычные повторяющиеся расчёты или разные платежи из общего остатка.','Fact: recurring transfer order. Hypothesis: regular transfers through an intermediary. Alternative: ordinary recurring settlements or unrelated payments from a shared balance.','Факт — аударым ретінің қайталануы. Болжам — делдал арқылы тұрақты аударымдар. Балама — әдеттегі қайталанатын есеп айырысу немесе ортақ қалдықтан жасалған әртүрлі төлемдер.'],['Для проверки нужны назначения платежей, точное время, остатки и операции вне выборки. Суммы разных маршрутов нельзя складывать как независимый денежный поток.','Verification requires payment purposes, exact times, balances and operations outside the sample. Amounts from different routes cannot be added as independent money flows.','Тексеру үшін төлем мақсаттары, нақты уақыт, қалдықтар және іріктемеден тыс операциялар қажет. Әртүрлі тізбектердің сомаларын тәуелсіз ақша ағыны ретінде қосуға болмайды.']
];
const map=new Map(catalog.map(([ru,en,kk])=>[ru,{ru,en,kk}]));let prefs={mode:'dark',skin:'classic',lang:'ru'};
try{const s=JSON.parse(localStorage.getItem('potok-preferences')||'{}');if(['dark','light'].includes(s.mode))prefs.mode=s.mode;if(['classic','minecraft','anime'].includes(s.skin))prefs.skin=s.skin;if(['ru','en','kk'].includes(s.lang))prefs.lang=s.lang;}catch{}
const originals=new WeakMap(),attributes=new WeakMap();
function translate(s){if(prefs.lang==='ru')return s;const value=s.trim(),item=map.get(value);if(item)return s.replace(value,item[prefs.lang]);
 const rules=[[/^Выбрано: (\d+)$/,['Selected: $1','Таңдалды: $1']],[/^Найдено: (\d+)$/,['Found: $1','Табылды: $1']],[/^(\d+) из (\d+) проверок пройдено · раскрыть$/,['$1 of $2 checks passed · expand','$2 тексерудің $1-і өтті · ашу']],[/^Клиент (\d+) · (.*)$/,['Client $1 · $2','Клиент $1 · $2']],[/^Группа (\d+) · (\d+) чел\.$/,['Group $1 · $2 clients','$1-топ · $2 клиент']],[/^Найдена цепочка · переводов: (\d+)$/,['Route found · transfers: $1','Тізбек табылды · аударымдар: $1']]];
 for(const [re,repl]of rules)if(re.test(value))return s.replace(value,value.replace(re,repl[prefs.lang==='en'?0:1]));const fragments=prefs.lang==='en'?[['анализ работает локально','local analysis'],['направленных связей','directed links'],['без связей','isolated'],['сообществ · локально','communities · local'],['(неполная)','(partial)'],[' дн',' days'],['Пересчёт','Recalculation']]:[['анализ работает локально','жергілікті талдау'],['направленных связей','бағытталған байланыс'],['без связей','оқшау'],['сообществ · локально','топ · жергілікті'],['(неполная)','(толық емес)'],[' дн',' күн'],['Пересчёт','Қайта есептеу']];
 for(const [ru,target]of fragments)s=s.replaceAll(ru,target);return s;}
const skip=node=>node.parentElement?.closest('script,style,pre,code,[data-no-translate]');
function translateDOM(){observer.disconnect();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(skip(n))continue;let record=originals.get(n);if(!record||n.nodeValue!==record.last)record={source:n.nodeValue};const next=translate(record.source);if(n.nodeValue!==next)n.nodeValue=next;record.last=next;originals.set(n,record);}
 for(const el of document.querySelectorAll('[placeholder],[aria-label],[title]')){if(el.closest('[data-no-translate]'))continue;let records=attributes.get(el)||{};for(const key of ['placeholder','aria-label','title']){if(!el.hasAttribute(key))continue;const value=el.getAttribute(key);let r=records[key];if(!r||value!==r.last)r={source:value};r.last=translate(r.source);el.setAttribute(key,r.last);records[key]=r;}attributes.set(el,records);}
 observer.observe(document.body,{subtree:true,childList:true,characterData:true});}
const observer=new MutationObserver(()=>translateDOM());
function apply(){document.documentElement.dataset.mode=prefs.mode;document.documentElement.dataset.skin=prefs.skin;document.documentElement.lang=prefs.lang;try{localStorage.setItem('potok-preferences',JSON.stringify(prefs));}catch{}const note=document.getElementById('locale-note');note.hidden=prefs.lang==='ru';note.textContent=prefs.lang==='en'?'UI language: English. Detailed analytical explanations, CSV and PDF reports remain in Russian.':'Интерфейс тілі: қазақша. Толық аналитикалық түсіндірмелер, CSV және PDF есептері орыс тілінде қалады.';translateDOM();}
const selectedTheme=prefs.skin==='classic'?prefs.mode:prefs.skin;
const toolbar=document.createElement('div');toolbar.className='preferences';toolbar.innerHTML='<label><span>Тема</span><select aria-label="Тема" id="pref-theme"><option value="dark">Тёмная</option><option value="light">Светлая</option><option value="minecraft">Minecraft</option><option value="anime">Аниме</option></select></label><label><span>Язык интерфейса</span><select aria-label="Язык интерфейса" id="pref-lang"><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select></label>';
document.querySelector('header')?.append(toolbar);const note=document.createElement('p');note.id='locale-note';note.className='locale-note';note.setAttribute('data-no-translate','');document.querySelector('header')?.after(note);
const themeSelect=document.getElementById('pref-theme');themeSelect.value=selectedTheme;
function setTheme(value){prefs.skin=['minecraft','anime'].includes(value)?value:'classic';prefs.mode=value==='light'||value==='anime'?'light':'dark';apply();}
themeSelect.onchange=()=>setTheme(themeSelect.value);
const langSelect=document.getElementById('pref-lang');langSelect.value=prefs.lang;langSelect.onchange=()=>{prefs.lang=langSelect.value;apply();};
const scenery=document.createElement('div');scenery.className='theme-scenery';scenery.setAttribute('aria-hidden','true');document.querySelector('header')?.after(scenery);
setTheme(selectedTheme);
})();
