import {loadData,loadControls,roles,roleColors,fmt,esc} from './data.js';
import {readState,writeState,link,getReview,toggleReview} from './state.js';
import {shell,showError} from './shell.js';
import {renderCard} from './card.js';
const view=new URLSearchParams(location.search).get('view')||'participants',titles={participants:'Участники',clusters:'Кластеры',review:'Список проверки',method:'Методика и устойчивость',controls:'Контрольные сценарии',exports:'Выгрузки'};
shell(titles[view]||titles.participants,view==='clusters'?3:view==='review'?5:2);
const main=document.querySelector('main');main.innerHTML=`<div class="page-heading"><div><h1>${titles[view]||titles.participants}</h1><p>Проверяйте гипотезы на наблюдаемых операциях</p></div><a class="secondary" href="${esc(link('/graph'))}">Открыть граф сети</a></div><div class="analytics-workspace"><div id="content"></div><aside id="client-card" class="client-panel" hidden></aside></div>`;
const content=document.getElementById('content');let data;
const table=(head,body)=>`<div class="table-wrap"><table><thead><tr>${head.map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;
const row=n=>`<tr><td><button class="gid-button" data-gid="${n.gid}">${n.gid}</button>${n.is_seed?'<span class="badge">seed</span>':''}${n.truncated_by_depth?'<span title="Граница наблюдения"> ◇</span>':''}</td><td><span class="role-dot" style="background:${roleColors[n.role]}"></span>${roles[n.role]}</td><td>${fmt(n.in_kzt)}</td><td>${fmt(n.out_kzt)}</td><td>${n.in_deg} / ${n.out_deg}</td><td><strong>${fmt(n.priority_score,3)}</strong></td><td>${n.cluster_id}</td></tr>`;
function bindRows(){for(const b of content.querySelectorAll('[data-gid]'))b.onclick=()=>writeState({gid:b.dataset.gid});}
function card(){const s=readState();main.querySelector('.page-heading>a').href=link('/graph');renderCard(document.getElementById('client-card'),data,s.gid,{close:()=>writeState({gid:''}),onSelect:gid=>writeState({gid})});document.querySelector('.analytics-workspace').classList.toggle('has-selection',data.byId.has(s.gid));}
function participants(){const s=readState();content.innerHTML=`<section class="card"><div class="panel-heading"><h2>Участники сети</h2><span class="muted">${fmt(data.nodes.length)} клиентов</span></div><div class="filters"><label>Поиск по gid<input id="participant-search" value="${esc(s.q)}" placeholder="Полный gid или его часть"></label><label>Роль<select id="role"><option value="">Все роли</option>${Object.entries(roles).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><label>Кластер<select id="cluster"><option value="">Все кластеры</option>${data.clusters.map(c=>`<option value="${c.cluster_id}">${c.cluster_id} · ${c.n_nodes} уч.</option>`).join('')}</select></label><label>Граница<select id="boundary"><option value="">Все участники</option><option value="only">Только граница</option><option value="exclude">Без границы</option></select></label></div><div id="participants-table"></div><div class="footer"><span id="count"></span><div><button id="prev">Назад</button> <button id="next">Далее</button></div></div></section><p class="note">Роль — гипотеза, приоритет — очередность проверки. ◇ означает обрыв наблюдения, а не доказанное удержание денег.</p>`;
 const extra=document.createElement('div');extra.className='filters extra-filters';extra.innerHTML=`<label>Глубина<select id="participant-depth"><option value="">Все колена</option>${[0,1,2,3,4].map(d=>`<option>${d}</option>`).join('')}</select></label><label class="check-label"><input id="participant-seed" type="checkbox">Только seed</label>`;content.querySelector('.filters').after(extra);document.getElementById('participant-depth').value=s.depth;document.getElementById('participant-depth').onchange=e=>writeState({depth:e.target.value,page:'0'});document.getElementById('participant-seed').checked=!!s.seed;document.getElementById('participant-seed').onchange=e=>writeState({seed:e.target.checked?'1':'',page:'0'});
 for(const id of ['role','cluster','boundary']){document.getElementById(id).value=s[id];document.getElementById(id).onchange=e=>writeState({[id]:e.target.value,page:'0'});}
 document.getElementById('participant-search').oninput=e=>{writeState({q:e.target.value,page:'0'},{replace:true});};rows();
}
function rows(){const s=readState();let nodes=data.nodes.filter(n=>n.gid.includes(s.q)&&(!s.depth||String(n.depth)===s.depth)&&(!s.seed||n.is_seed)&&(!s.role||n.role===s.role)&&(!s.cluster||String(n.cluster_id)===s.cluster)&&(s.boundary!=='only'||n.truncated_by_depth)&&(s.boundary!=='exclude'||!n.truncated_by_depth));const keys=['in_kzt','out_kzt','in_deg','priority_score','cluster_id'];const sort=keys.includes(s.sort)?s.sort:'priority_score';nodes.sort((a,b)=>(a[sort]-b[sort])*(s.order==='asc'?1:-1)||a.gid.localeCompare(b.gid));const page=Math.min(Math.max(0,Number(s.page)||0),Math.max(0,Math.ceil(nodes.length/20)-1));
 const headings=['Клиент / gid','Роль-гипотеза',...['Вход, ₸','Выход, ₸','Связи вх. / исх.','Приоритет','Кластер'].map((t,i)=>`<button class="sort-button" data-sort="${keys[i]}" aria-label="Сортировать: ${t}">${t} ${s.sort===keys[i]?(s.order==='asc'?'↑':'↓'):'↕'}</button>`)];
 document.getElementById('participants-table').innerHTML=table(headings,nodes.slice(page*20,page*20+20).map(row).join('')||'<tr><td colspan="7">Нет участников по заданным фильтрам.</td></tr>');document.getElementById('count').textContent=nodes.length?`${page*20+1}–${Math.min(page*20+20,nodes.length)} из ${fmt(nodes.length)}`:'0 участников';document.getElementById('prev').disabled=!page;document.getElementById('next').disabled=(page+1)*20>=nodes.length;document.getElementById('prev').onclick=()=>writeState({page:String(page-1)});document.getElementById('next').onclick=()=>writeState({page:String(page+1)});for(const b of content.querySelectorAll('[data-sort]'))b.onclick=()=>writeState({sort:b.dataset.sort,order:s.sort===b.dataset.sort&&s.order==='desc'?'asc':'desc',page:'0'});bindRows();}
function clusters(){const s=readState(),list=[...data.clusters].sort((a,b)=>b.sum_kzt_internal-a.sum_kzt_internal);content.innerHTML=`<section class="card"><h2>${data.clusters.length} сообществ переводов</h2><p class="muted">Louvain по сумме переводов на неориентированной проекции. Это сообщества, а не слабосвязные компоненты (${data.summary.weak_components}).</p><label>Выбрать кластер<select id="cluster-select"><option value="">Все кластеры</option>${list.map(c=>`<option value="${c.cluster_id}">Кластер ${c.cluster_id} · ${c.n_nodes} участников</option>`).join('')}</select></label>${table(['Кластер','Участники / seed','Внутренний оборот, ₸','Действие'],list.filter(c=>!s.cluster||String(c.cluster_id)===s.cluster).map(c=>`<tr><td><button data-cluster="${c.cluster_id}">Кластер ${c.cluster_id}</button></td><td>${c.n_nodes} / ${c.n_seed}</td><td>${fmt(c.sum_kzt_internal)}</td><td><a href="${esc(link('/graph',{cluster:String(c.cluster_id),layout:'cluster',hops:''}))}">На графе</a></td></tr><tr><td colspan="4" class="wrap cluster-hypothesis">${esc(c.hypothesis)}</td></tr>`).join(''))}</section>${s.cluster?`<section class="card"><h2>Участники кластера ${esc(s.cluster)}</h2>${table(['Клиент / gid','Роль','Вход, ₸','Выход, ₸','Связи','Приоритет','Кластер'],data.nodes.filter(n=>String(n.cluster_id)===s.cluster).map(row).join(''))}</section>`:''}`;document.getElementById('cluster-select').value=s.cluster;document.getElementById('cluster-select').onchange=e=>writeState({cluster:e.target.value});for(const b of content.querySelectorAll('[data-cluster]'))b.onclick=()=>writeState({cluster:b.dataset.cluster});bindRows();}
function review(){const nodes=[...getReview()].map(id=>data.byId.get(id)).filter(Boolean).sort((a,b)=>b.priority_score-a.priority_score);content.innerHTML=`<section class="card"><div class="panel-heading"><h2>Выбрано ${nodes.length} из 50</h2><button id="export-review" class="primary" ${nodes.length?'':'disabled'}>Скачать CSV</button></div><p>Выбор сохраняется в этой вкладке между переходами. Добавляйте клиентов из их карточек.</p>${table(['Клиент','Роль','Приоритет','Действие'],nodes.map(n=>`<tr><td><button class="gid-button" data-gid="${n.gid}">${n.gid}</button></td><td>${roles[n.role]}</td><td>${fmt(n.priority_score,3)}</td><td><button data-remove="${n.gid}">Убрать</button></td></tr>`).join('')||'<tr><td colspan="4">Список пуст. Откройте участника и добавьте его в список проверки.</td></tr>')}<p class="note">Это список для изучения, не автоматическое решение о блокировке. При импорте CSV задайте для gid тип «текст».</p></section>`;bindRows();for(const b of content.querySelectorAll('[data-remove]'))b.onclick=()=>{toggleReview(b.dataset.remove);card();};document.getElementById('export-review').onclick=()=>{const q=new URLSearchParams();nodes.forEach(n=>q.append('gid',n.gid));location.href='/download/review.csv?'+q;};}
function method(){content.innerHTML=`<section class="card prose"><h2>Как читать результаты</h2><p>Роль — гипотеза. role_score — сила правила, а не вероятность виновности. priority_score задаёт очередность проверки.</p><p>Наблюдение ограничено исходящим обходом от seed, четырьмя шагами и порогом 5 000 ₸. Отсутствие исходящих на границе не доказывает удержание денег. Входящие seed могут быть неполными.</p><p>Сумма переводов в выборке не является уникальным капиталом сети. Последовательность переводов и FIFO-сопоставления не доказывают движение одних и тех же средств.</p><p>Зелёный означает выбор или действие. Расстояние между узлами — компоновка, не география и не доказательная сила. Чувствительность роли к трём настройкам порогов не является статистической достоверностью.</p><a href="/case-study">Законченный разбор реального клиента</a> · <a href="/demo">Сценарий разбора</a></section><section class="card"><h2>Удаление ключевых узлов</h2><p>Сравнение со случайным удалением: 30 повторов, фиксированный seed. Анализ связности, не прогноз поведения.</p>${table(['Сценарий','Крупнейшая компонента','Компоненты','Изоляты','Случайное удаление: медиана (диапазон)'],data.resilience.map(r=>`<tr><td>Топ-${r.removed_count}</td><td>${r.baseline_largest} → ${r.largest_component}</td><td>${r.components}</td><td>${r.isolates}</td><td>${fmt(r.random_largest_median)} (${r.random_largest_min}–${r.random_largest_max})</td></tr>`).join(''))}</section><section class="card"><h2>Три случая для разбора</h2><div class="case-grid">${data.demo.map(n=>`<button data-gid="${n.gid}"><strong>${roles[n.role]}</strong><p>${n.gid}</p><small>${esc(n.evidence)}</small></button>`).join('')}</div></section>`;bindRows();}
async function controls(){content.innerHTML='<div class="card">Загрузка контрольных сценариев…</div>';try{const r=await loadControls();content.innerHTML=`<section class="card"><h2>${r.passed} из ${r.total} проверок пройдено</h2><p>Искусственные сценарии проверяют те же правила. Они не подменяют реальные данные.</p>${table(['Сценарий','Ожидание','Результат','Статус','Основание'],r.cases.map(c=>`<tr><td>${esc(c.name)}</td><td>${roles[c.expected]}</td><td>${roles[c.actual]}</td><td>${c.passed?'Пройден':'Ошибка'}</td><td class="wrap">${esc(c.reason)}</td></tr>`).join(''))}<p class="note">${esc(r.limitation)}</p><a href="/controls-report">Полный отчёт</a></section>`;}catch(e){showError(content,e);}}
function exports(){content.innerHTML=`<section class="card"><h2>Выгрузки из текущего расчёта</h2><div class="export-list">${[['nodes_roles','Роли всех участников'],['clusters','Сообщества'],['top_nodes','Топ-50 для проверки'],['temporal_matches','Временные сопоставления']].map(([f,t])=>`<a href="/download/${f}.csv"><span>${t}</span><span>CSV ↓</span></a>`).join('')}</div><p>Идентификаторы gid, src и dst импортируйте как текст, чтобы сохранить точность.</p><a href="${esc(link('/analytics?view=review'))}">Мой список проверки</a></section>`;}
try{data=await loadData();const render=()=>{if(view==='clusters')clusters();else if(view==='review')review();else if(view==='method')method();else if(view==='controls')controls();else if(view==='exports')exports();else participants();card();};render();
 window.addEventListener('potok-state',()=>{if(view==='participants'){const active=document.activeElement;if(active?.id==='participant-search'){rows();card();return;}}render();});window.addEventListener('popstate',render);window.addEventListener('potok-review',()=>{if(view==='review')review();});
}catch(e){showError(content,e);}
