import {loadData,fmt,roles,esc} from './data.js';
import {readState,writeState,visibleGraph} from './state.js';
import {shell,showError} from './shell.js';
import {Layout} from './layout.js';
import {Scene2D} from './scene2d.js';
import {renderCard} from './card.js';
import {controls} from './controls.js';
import {renderLegend} from './legend.js';
shell('Граф сети',1);
const main=document.querySelector('main');main.innerHTML=`<div class="page-heading"><div><h1>Граф сети</h1><p>Исследуйте связи, роли и движение средств</p></div><span class="badge">Вся наблюдаемая сеть</span></div><div id="graph-controls" class="card control-card"></div><p id="graph-message" role="status" aria-live="polite"></p><div class="graph-workspace"><section class="scene-panel"><div class="scene-heading"><strong id="graph-count">Загрузка сети…</strong><span id="layout-caption"></span></div><div id="scene" class="scene"><div id="tooltip" class="graph-tooltip" hidden></div><div id="empty-graph" class="empty-overlay" hidden>Нет узлов по заданным фильтрам. Сбросьте фильтры.</div></div><div class="camera-tools"><button data-camera="fit">Показать всю сеть</button><button data-camera="top">Вид сверху</button><button data-camera="reset">Сбросить камеру</button><button data-camera="in" aria-label="Приблизить">+</button><button data-camera="out" aria-label="Отдалить">−</button></div><div id="edge-info" class="edge-info" hidden></div><div id="legend" class="graph-legend"></div><small class="scene-help">Мышь — вращение в 3D / сдвиг в 2D · колесо — масштаб · правая кнопка — сдвиг в 3D. Расстояние — компоновка, не география и не сила доказательства.</small></section><aside id="client-card" class="client-panel" hidden aria-label="Карточка выбранного клиента"></aside></div>`;
try{
 const data=await loadData(),layout=new Layout(data.nodes),sync=controls(document.getElementById('graph-controls'),data),host=document.getElementById('scene'),message=document.getElementById('graph-message'),tooltip=document.getElementById('tooltip');let scene,mode,version=0,previousLayout,previousGid,previousFilter,failed3D=false;
 const select=gid=>writeState({gid});
 const handlers={onSelect:select,onEdge:e=>{const el=document.getElementById('edge-info');el.hidden=false;el.textContent=`${e.src} → ${e.dst} · ${fmt(e.sum_kzt,2)} ₸ · ${fmt(e.n_tx)} операций`;},onHover:(n,event)=>{tooltip.hidden=!n;if(!n)return;tooltip.innerHTML=`<strong>${esc(n.gid)}</strong><br>${roles[n.role]} · приоритет ${fmt(n.priority_score,3)}<br>Вход ${fmt(n.in_kzt)} ₸ · выход ${fmt(n.out_kzt)} ₸<br>Глубина ${n.depth}${n.truncated_by_depth?' · ◇ граница наблюдения':''}`;const r=host.getBoundingClientRect();tooltip.style.left=`${Math.max(4,Math.min(event.clientX-r.left+12,host.clientWidth-300))}px`;tooltip.style.top=`${Math.max(4,Math.min(event.clientY-r.top+12,host.clientHeight-110))}px`;},onFailure:reason=>{failed3D=true;message.textContent=reason;writeState({mode:'2d'},{replace:true});}};
 async function render(){const ticket=++version,s=readState();sync();const graph=visibleGraph(data,s),positions=await layout.get(s.layout==='cluster'?'cluster':'depth');if(ticket!==version)return;
  if(!scene||mode!==s.mode){scene?.dispose();if(s.mode==='3d'&&!failed3D){try{const {Scene3D}=await import('./scene3d.js');if(ticket!==version)return;scene=new Scene3D(host,handlers);mode='3d';}catch(e){failed3D=true;message.textContent=`3D недоступен: ${e.message}. Включён рабочий 2D-режим.`;writeState({mode:'2d'},{replace:true});return;}}else{scene=new Scene2D(host,handlers);mode='2d';}previousLayout=null;}
  if(s.mode==='3d'&&failed3D){message.textContent='WebGL недоступен в этом браузере. Используется 2D-режим.';writeState({mode:'2d'},{replace:true});return;}
  const panel=document.getElementById('client-card');renderCard(panel,data,s.gid,{close:()=>writeState({gid:'',hops:''}),onSelect:select});document.querySelector('.graph-workspace').classList.toggle('has-selection',!panel.hidden);
  scene.setData(graph,positions,s);scene.resize();const filter=[s.role,s.cluster,s.depth,s.seed,s.hops,s.direction].join('|');if(previousLayout!==s.layout||previousFilter!==filter)scene.fit();if(previousGid!==s.gid&&graph.nodes.some(n=>n.gid===s.gid))scene.focus(s.gid);previousLayout=s.layout;previousGid=s.gid;previousFilter=filter;
  document.getElementById('graph-count').textContent=`${fmt(graph.nodes.length)} / ${fmt(data.nodes.length)} узлов · ${fmt(graph.edges.length)} / ${fmt(data.edges.length)} связей`;
  document.getElementById('layout-caption').textContent=s.layout==='cluster'?'Пространственные группы сообществ':'Колена 0 → 1 → 2 → 3 → 4';document.getElementById('empty-graph').hidden=graph.nodes.length>0;document.getElementById('edge-info').hidden=true;renderLegend(document.getElementById('legend'),s,graph.nodes);
  if(s.gid&&!data.byId.has(s.gid))message.textContent=`Клиент ${s.gid} отсутствует в выборке. Проверьте полный gid.`;
  else if(s.gid&&!graph.nodes.some(n=>n.gid===s.gid)){message.innerHTML='Выбранный клиент скрыт фильтрами. <button id="reveal-node">Показать клиента и сбросить фильтры</button>';document.getElementById('reveal-node').onclick=()=>{previousGid=null;writeState({role:'',cluster:'',depth:'',seed:'',hops:''});};}
  else if(!failed3D)message.textContent=s.hops?`Окружение: ${s.hops} перехода. ${s.direction==='all'?'Обход без учёта направления; стрелки сохраняют направление переводов.':s.direction==='in'?'Обход против направления переводов.':'Обход по направлению переводов.'}`:'Зелёный означает выбор или действие. Размер узла отражает приоритет проверки.';
 }
 const update=()=>render().catch(e=>showError(message,e));window.addEventListener('potok-state',update);window.addEventListener('popstate',update);
 document.getElementById('graph-search').onsubmit=e=>{e.preventDefault();const gid=document.getElementById('graph-gid').value.trim();if(readState().gid===gid)scene.focus(gid);else select(gid);};
 for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>{if(!scene)return;if(b.dataset.camera==='in'||b.dataset.camera==='out')scene.zoom(b.dataset.camera==='in'?.8:1.25);else{scene.fit(b.dataset.camera==='top');if(b.dataset.camera==='fit'&&readState().hops)writeState({hops:''});}};
 window.addEventListener('pagehide',()=>{scene?.dispose();scene=null;layout.dispose();},{once:true});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});await render();
}catch(e){showError(main,e);}
