import {radius,thickness,edgePoints} from './geometry.js';
import {nodeColor} from './legend.js';
export class Scene2D{
 constructor(host,handlers){this.host=host;this.handlers=handlers;this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','2D-граф. Перетаскивание перемещает сеть, колесо меняет масштаб.');host.append(this.canvas);this.ctx=this.canvas.getContext('2d');if(!this.ctx)throw Error('Canvas 2D недоступен в браузере.');this.scale=1;this.x=0;this.y=0;this.abort=new AbortController();const opts={signal:this.abort.signal};let down;
  this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,ox:this.x,oy:this.y,moved:false};this.canvas.setPointerCapture(e.pointerId);},opts);
  this.canvas.addEventListener('pointermove',e=>{if(down){if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;if(down.moved){this.x=down.ox+e.clientX-down.x;this.y=down.oy+e.clientY-down.y;this.invalidate();}}else this.handlers.onHover?.(this.hit(e),e);},opts);
  this.canvas.addEventListener('pointerup',e=>{if(down&&!down.moved){const n=this.hit(e);if(n)this.handlers.onSelect(n.gid);else{const edge=this.hitEdge(e);if(edge)this.handlers.onEdge(edge);}}down=null;},opts);
  this.canvas.addEventListener('pointerleave',()=>this.handlers.onHover?.(null),opts);
  this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY>0?1.12:.89);},{...opts,passive:false});this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.resize();
 }
 project(p){return [p[0]+p[2]*.42,p[1]+p[2]*.18];}
 screenRadius(n){return Math.max(2,Math.min(12,radius(n)*this.scale));}
 screen(p){const [x,y]=this.project(p);return [x*this.scale+this.x,-y*this.scale+this.y];}
 setData(graph,positions,state){this.graph=graph;this.positions=positions;this.state=state;this.neighbors=new Set();for(const e of graph.edges)if(e.src===state.gid||e.dst===state.gid){this.neighbors.add(e.src);this.neighbors.add(e.dst);}this.paths=graph.edges.map(e=>edgePoints(e,positions));this.invalidate();}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(this.width){this.x+=(w-this.width)/2;this.y+=(h-this.height)/2;}this.width=w;this.height=h;const ratio=Math.min(devicePixelRatio,2);this.canvas.width=w*ratio;this.canvas.height=h*ratio;this.canvas.style.width='100%';this.canvas.style.height='100%';this.ctx.setTransform(ratio,0,0,ratio,0,0);this.invalidate();}
 invalidate(){if(this.frame||this.disposed)return;this.frame=requestAnimationFrame(()=>{this.frame=null;this.draw();});}
 draw(){if(!this.graph||this.disposed)return;const ctx=this.ctx;ctx.clearRect(0,0,this.host.clientWidth,this.host.clientHeight);ctx.fillStyle='#f8faf8';ctx.fillRect(0,0,this.host.clientWidth,this.host.clientHeight);
  this.paths.forEach((path,i)=>{const e=this.graph.edges[i],active=e.src===this.state.gid||e.dst===this.state.gid,points=path.map(p=>this.screen(p));ctx.strokeStyle=active?'#15803d':this.state.gid?'#e3e8e4':'#b9c2bb';ctx.lineWidth=Math.max(.5,thickness(e)*this.scale)*(active?2:1);ctx.beginPath();points.forEach(([x,y],j)=>j?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();const target=this.screen(this.positions[e.dst]);let j=points.length-2;while(j>0&&Math.hypot(points[j][0]-target[0],points[j][1]-target[1])<18)j--;const a=points[j],b=points[j+1],angle=Math.atan2(b[1]-a[1],b[0]-a[0]),r=active?6:4;ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(a[0]+r*Math.cos(angle),a[1]+r*Math.sin(angle));ctx.lineTo(a[0]+r*Math.cos(angle+2.5),a[1]+r*Math.sin(angle+2.5));ctx.lineTo(a[0]+r*Math.cos(angle-2.5),a[1]+r*Math.sin(angle-2.5));ctx.closePath();ctx.fill();});
  this.graph.nodes.forEach(n=>{const [x,y]=this.screen(this.positions[n.gid]),r=this.screenRadius(n);ctx.fillStyle=nodeColor(n,this.state,this.neighbors);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#637067';ctx.lineWidth=1;if(n.is_seed){ctx.beginPath();ctx.arc(x,y,r+3,0,Math.PI*2);ctx.stroke();}if(n.truncated_by_depth){ctx.beginPath();ctx.moveTo(x,y-r-3);ctx.lineTo(x+r+3,y);ctx.lineTo(x,y+r+3);ctx.lineTo(x-r-3,y);ctx.closePath();ctx.stroke();}});
  const labels=this.graph.nodes.filter(n=>n.gid===this.state.gid||this.neighbors.has(n.gid)||(this.scale>2&&this.inView(n))).sort((a,b)=>(b.gid===this.state.gid)-(a.gid===this.state.gid)||b.priority_score-a.priority_score).slice(0,16);ctx.font='11px Segoe UI';ctx.fillStyle='#26362b';const occupied=[];labels.forEach(n=>{const [x,y]=this.screen(this.positions[n.gid]),text=n.gid===this.state.gid?n.gid:'…'+n.gid.slice(-7),w=ctx.measureText(text).width,rect=[x+8,y-20,x+8+w,y-5];if(rect[0]<0||rect[2]>this.host.clientWidth||rect[1]<0||rect[3]>this.host.clientHeight||occupied.some(r=>rect[0]<r[2]+5&&rect[2]>r[0]-5&&rect[1]<r[3]+3&&rect[3]>r[1]-3))return;occupied.push(rect);ctx.fillText(text,x+8,y-8);});
 }
 inView(n){const [x,y]=this.screen(this.positions[n.gid]);return x>0&&x<this.host.clientWidth&&y>0&&y<this.host.clientHeight;}
 point(e){const r=this.canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
 hit(e){if(!this.graph)return null;const [x,y]=this.point(e);return [...this.graph.nodes].reverse().find(n=>{const p=this.screen(this.positions[n.gid]);return Math.hypot(p[0]-x,p[1]-y)<Math.max(6,this.screenRadius(n)+2);});}
 hitEdge(e){const [x,y]=this.point(e);let best=5,found;this.paths.forEach((path,i)=>{const p=path.map(a=>this.screen(a));for(let j=1;j<p.length;j++){const a=p[j-1],b=p[j],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy||1))),d=Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy);if(d<best){best=d;found=this.graph.edges[i];}}});return found;}
 fit(){if(!this.graph?.nodes.length)return;const ps=this.graph.nodes.map(n=>this.project(this.positions[n.gid])),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);this.scale=Math.min((this.host.clientWidth-70)/(maxX-minX+30),(this.host.clientHeight-70)/(maxY-minY+30));this.x=this.host.clientWidth/2-(maxX+minX)/2*this.scale;this.y=this.host.clientHeight/2+(maxY+minY)/2*this.scale;this.invalidate();}
 focus(gid){if(!this.positions?.[gid])return;const [x,y]=this.project(this.positions[gid]);this.scale=2.5;this.x=this.host.clientWidth/2-x*this.scale;this.y=this.host.clientHeight/2+y*this.scale;this.invalidate();}
 zoom(factor){const cx=this.host.clientWidth/2,cy=this.host.clientHeight/2,next=Math.max(.08,Math.min(15,this.scale/factor)),ratio=next/this.scale;this.x=cx+(this.x-cx)*ratio;this.y=cy+(this.y-cy)*ratio;this.scale=next;this.invalidate();}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.abort.abort();this.observer.disconnect();this.canvas.remove();}
}
