import {loadData,fmt,esc} from './data.js';
import {link,readState} from './state.js';
const icons=['M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z','M5 6l14 2-7 11z M5 6l7 13 M5 3a3 3 0 1 0 0 6a3 3 0 0 0 0-6 M19 5a3 3 0 1 0 0 6a3 3 0 0 0 0-6 M12 16a3 3 0 1 0 0 6a3 3 0 0 0 0-6','M12 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M4 21v-3a8 6 0 0 1 16 0v3','M4 4h6v6H4z M14 14h6v6h-6z M14 4h6v6h-6z M4 14h6v6H4z','M3 6h15l-4-4 M18 6l-4 4 M21 18H6l4-4 M6 18l4 4','M6 3h14v18H4V3z M8 9l2 2 5-5 M8 16h8'];
const items=[['Обзор','/'],['Граф сети','/graph'],['Участники','/analytics'],['Кластеры','/analytics?view=clusters'],['Цепочки','/routes'],['Список проверки','/analytics?view=review']];
export function shell(title,active){document.querySelector('header')?.remove();const side=document.createElement('aside');side.className='sidebar';side.innerHTML=`<a class="brand" href="/"><span class="brand-mark">п</span><span>Поток<small>Аналитика финансовых связей</small></span></a><nav aria-label="Главная навигация">${items.map(([t,p],i)=>`<a data-nav="${p}" href="${esc(link(p))}" ${i===active?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[i]}"/></svg>${t}</a>`).join('')}</nav><div class="sidebar-bottom"><a href="/copilot">Copilot</a><a href="/weekly">По неделям</a><a href="/patterns">Повторяющиеся маршруты</a><a href="${esc(link('/analytics?view=method'))}">Методика и устойчивость</a><a href="${esc(link('/analytics?view=controls'))}">Контрольные сценарии</a><a href="${esc(link('/analytics?view=exports'))}">Выгрузки</a><div class="local-status"><i></i> Локальная рабочая среда</div><small>Данные остаются на компьютере</small></div>`;document.body.prepend(side);
 document.title=`Поток · ${title}`;document.body.classList.toggle('graph-page',active===1);
 const top=document.createElement('header');top.className='topbar';top.innerHTML=`<div class="section-title">${esc(title)}</div><form id="global-search" role="search"><label class="sr-only" for="global-gid">Поиск по полному gid</label><input id="global-gid" placeholder="Поиск по gid" autocomplete="off"><button aria-label="Найти клиента">Найти</button></form><div class="dataset"><span id="dataset-period">Загрузка периода…</span><small id="dataset-status" role="status">Загрузка данных</small></div>`;side.after(top);
 const theme=document.createElement('link');theme.rel='stylesheet';theme.href='/themes.css';document.head.append(theme);const bridge=document.createElement('style');bridge.textContent=`.sidebar,.topbar,.client-panel,.scene-panel{background:var(--panel);color:var(--ink);border-color:var(--line)}.priority-row,.brand,.quick-links>a,.facts strong,label input,label select{color:var(--ink)}.priority-row:hover,.cluster-hypothesis,.graph-tooltip,.empty-overlay{background:var(--surface);color:var(--ink)}.sidebar{overflow-y:auto}.sidebar-bottom{gap:10px}.topbar{height:auto;min-height:84px}.locale-note{margin-left:232px}.preferences{margin-left:0}.scene,.preview-scene{color:#151a16}.table-wrap{max-height:560px}.topbar .preferences{flex-wrap:nowrap}@media(max-width:700px){.locale-note{margin-left:0}}`;document.head.append(bridge);const preferences=document.createElement('script');preferences.src='/preferences.js';document.body.append(preferences);
 top.querySelector('form').onsubmit=e=>{e.preventDefault();location.href=link('/graph',{gid:top.querySelector('input').value.trim()});};
 side.querySelector('.brand').dataset.nav='/';for(const a of side.querySelectorAll('.sidebar-bottom>a'))a.dataset.nav=new URL(a.href).pathname+new URL(a.href).search;
 const refresh=()=>{for(const a of side.querySelectorAll('[data-nav]'))a.href=link(a.dataset.nav);top.querySelector('input').value=readState().gid;};window.addEventListener('potok-state',refresh);window.addEventListener('popstate',refresh);refresh();
 loadData().then(d=>{document.getElementById('dataset-period').textContent=`${d.summary.start} — ${d.summary.end}`;document.getElementById('dataset-status').textContent=`${fmt(d.nodes.length)} участников · данные загружены`;}).catch(()=>{document.getElementById('dataset-period').textContent='Период недоступен';document.getElementById('dataset-status').textContent='Ошибка загрузки';});
}
export function showError(el,error){el.innerHTML=`<div class="error" role="alert"><strong>Не удалось загрузить данные</strong><p>${esc(error.message)}</p><button onclick="location.reload()">Повторить загрузку</button></div>`;}
